import type { Invoice } from "../types";

export const SEED_INVOICES: Invoice[] = [
  {
    id: "RT3080", status: "paid",
    createdAt: "2021-08-18", paymentDue: "2021-08-19", paymentTerms: 1,
    description: "Re-branding", clientName: "Jensen Huang", clientEmail: "jensenh@mail.com",
    senderAddress: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    clientAddress: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    items: [{ name: "Brand Guidelines", quantity: 1, price: 1800.90, total: 1800.90 }],
    total: 1800.90,
  },
  {
    id: "XM9141", status: "pending",
    createdAt: "2021-08-21", paymentDue: "2021-09-20", paymentTerms: 30,
    description: "Graphic Design", clientName: "Alex Grim", clientEmail: "alexgrim@mail.com",
    senderAddress: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    clientAddress: { street: "84 Church Way", city: "Bradford", postCode: "BD1 9PB", country: "United Kingdom" },
    items: [
      { name: "Banner Design", quantity: 1, price: 156.00, total: 156.00 },
      { name: "Email Design",  quantity: 2, price: 200.00, total: 400.00 },
    ],
    total: 556.00,
  },
  {
    id: "RG0314", status: "paid",
    createdAt: "2021-09-01", paymentDue: "2021-10-01", paymentTerms: 30,
    description: "Website Redesign", clientName: "John Morrison", clientEmail: "jm@myco.com",
    senderAddress: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    clientAddress: { street: "79 Dover Road", city: "Westhall", postCode: "IP19 3PF", country: "United Kingdom" },
    items: [{ name: "Website Redesign", quantity: 1, price: 14002.33, total: 14002.33 }],
    total: 14002.33,
  },
  {
    id: "RT2080", status: "pending",
    createdAt: "2021-10-11", paymentDue: "2021-10-12", paymentTerms: 1,
    description: "Logo Concept", clientName: "Alysa Warner", clientEmail: "alysaw@email.co.uk",
    senderAddress: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    clientAddress: { street: "45 Arbour Lane", city: "Clacton-on-Sea", postCode: "CO15 4DG", country: "United Kingdom" },
    items: [{ name: "Logo Sketches", quantity: 1, price: 102.04, total: 102.04 }],
    total: 102.04,
  },
  {
    id: "AA1449", status: "pending",
    createdAt: "2021-10-18", paymentDue: "2021-11-17", paymentTerms: 30,
    description: "Re-branding", clientName: "Mellisa Clarke", clientEmail: "mellisa@clarke.com",
    senderAddress: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    clientAddress: { street: "46 Elm Road", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    items: [{ name: "Brand Guidelines", quantity: 1, price: 4032.33, total: 4032.33 }],
    total: 4032.33,
  },
  {
    id: "TY9141", status: "pending",
    createdAt: "2021-10-31", paymentDue: "2021-11-30", paymentTerms: 30,
    description: "Landing Page Design", clientName: "Thomas Wayne", clientEmail: "thomas@dc.com",
    senderAddress: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    clientAddress: { street: "3940 Hegal Place", city: "Gotham", postCode: "G1 2JK", country: "United States" },
    items: [{ name: "Landing Page", quantity: 1, price: 6155.91, total: 6155.91 }],
    total: 6155.91,
  },
  {
    id: "FV2353", status: "draft",
    createdAt: "2021-11-12", paymentDue: "2021-12-12", paymentTerms: 30,
    description: "Logo Re-design", clientName: "Anita Wainwright", clientEmail: "anita@email.co.uk",
    senderAddress: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    clientAddress: { street: "48 Grand Parliament Lane", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    items: [{ name: "Logo Re-design", quantity: 1, price: 3102.04, total: 3102.04 }],
    total: 3102.04,
  },
];